name: Docker to ECR
on:
 workflow_dispatch: 
  push:
   branches:
     - main

  jobs:
  build-and-push:
      name: Build a docker image and push to ECR
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{secret.AWS_ACCESS_KEY_ID}}
         aws-ssecret-access-key: ${{secret.AWS_SECRET_ACCESS_KEY}}
         aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Tag Docker image
        run: docker tag my-image:latest 445952381501.dkr.ecr.us-east-2.amazonaws.com/ray:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 445952381501.dkr.ecr.us-east-2.amazonaws.com/ray:latest

      # - name: Login to AWS ECR
      #   id: login-aws-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push docker images to AWS ECR
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        # env: 
        #  ECR_REGISTRY: ${{steps.login-aws-ecr.outputs.registry}}
        #  ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
        #  IMAGE_TAG: latest
        # run:
        #   docker builds -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    
  
